name: Validate Terraform
on: [push]

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    environment: development
    env:
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.1
    - name: Terraform init eks-cluster
      id: init
      run: terraform init eks-cluster
      working-directory: ${{ github.workspace }}/eks-cluster
    - name: Terraform validate
      id: validate
      run: terraform validate
    - name: Terraform init eks-config
      id: init
      run: terraform init
      working-directory: ${{ github.workspace }}/eks-config
    - name: Terraform validate eks-config
      id: validate
      run: terraform validate
